<?php
namespace App\Exceptions;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

trait ExceptionTrait
{
    public function apiException($request, $e){
        if ($this->isModel($e)){
            return response()->json([
                'error'=>"Product Model Not Found"
            ],Response::HTTP_NOT_FOUND);
        }
        if ($this->isHttp($e)){
            //có thể tách tiếp
            // return $this->HttpResponse($e);
            return response()->json([
                'error'=>"Incorect route"
            ],Response::HTTP_NOT_FOUND);
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub

    }
//    protected function HttpResponse($e){
//        return response()->json([
//            'error'=>"Incorect route"
//        ],Response::HTTP_NOT_FOUND);
//    }
    protected function isModel($e){
        return $e instanceof ModelNotFoundException;
    }
    protected function isHttp($e){
        return $e instanceof NotFoundHttpException;
    }
}