<?php

namespace App\Exceptions;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }
    //nếu không có hàm render thì thêm vào
    public function render($request, Throwable $e)
    {
        if ($request->expectsJson()){
            if ($e instanceof ModelNotFoundException){
                return response()->json([
                    'error'=>"Product Model Not Found"
                ],Response::HTTP_NOT_FOUND);
            }
            if ($e instanceof NotFoundHttpException){
                return response()->json([
                    'error'=>"Incorect route"
                ],Response::HTTP_NOT_FOUND);
            }
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
